import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fonts = localFont({
  src: [
    {
      path: "fonts/Articulat-CF.ttf",
      style: "normal",
    },
    {
      path: "fonts/PowerGrotesk-Regular.ttf",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full min-h-screen flex flex-col m-auto ${fonts.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
